services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: xxi0ndb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordxxi0n
    ports:
      - "5432:5432"
    command:
      - postgres
      - -N
      - '1000'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
